### ISSUE TITLE
Doesn't work in WorkManager

### ISSUE THREAD

**Issue by sunnykinger** [patloew/CoLocation#3] opened 2021-02-23 13:52 UTC
I was trying to use this inside CoroutineWorker, but it doesn't seem to return any result. 

inside doWork() I am using this

**Comment by patloew** [comment] 2021-04-11 10:28
Can you please provide an example project where the issue can be reproduced?

**Comment by patloew** [comment] 2021-07-16 06:38
Closing this, since no further information was provided.

**Closed as completed by patloew** 2021-07-16 06:38 UTC
